# Generated by Django 5.0.2 on 2024-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='user_avatars/default_avatar.png', upload_to='user_avatars/'),
        ),
    ]
