# Generated by Django 5.0.3 on 2024-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='media/user_avatars/default_avatar.png', upload_to='user_avatars/'),
        ),
    ]
